import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[window]
decorations = "Full"
opacity = 0.9
startup_mode = "Maximized"

[font]
size = 12
glyph_offset = {x = 0, y = 0}

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true
